name: BagOfGold
main: one.lindegaard.BagOfGold.BagOfGold
version: ${version}
description: Use BagOfGold as an Economy plugin
dev-url: http://dev.bukkit.org/server-mods/bagofgold/
author: Rocologo
depend: [Vault]
loadbefore: [Essentials, Citizens2]
softdepend: [MobHunting]

commands:
  bagofgold:
    description: Allows you to configure mobhunt
    permission: bagofgold.cmd
    aliases: [bag,bog,money,gold]
    usage: /<command> command

permissions:
  bagofgold.cmd:
    description: Allows a player to use the mobhunt command
    default: true
  bagofgold.update:
    description: Allows a player to update the plugin
    default: op
    children:
      bagofgold.cmd: true
  bagofgold.reload:
    description: Allows you to reload the configuration
    default: op
    children:
      bagofgold.cmd: true
  bagofgold.version:
    description: Allows you to get plugin version.
    default: true
    children:
      bagofgold.cmd: true
  bagofgold.debug:
    description: Allows you to enable/disable debugmode and see debug information in the server console.
    default: op
    children:
      bagofgold.cmd: true
